### ISSUE TITLE
Data hidden symbol shown when data is visible

### ISSUE THREAD

**Issue by thomas-fred** [nismod/irv-jamaica#195]
[An example](https://jamaica.infrastructureresilience.org/exposure?lat=18.05933&lon=-77.72317&zoom=14.59&assets=true&hazards=false&buildings=false&buildingsStyle=type&regions=false&regionsStyle=boundaries&hazardsStyle=&terrestrialStyle=landuse&marineStyle=habitat&netTree=03&droughtStyle=adaptation&assetsStyle=type&terrestrial=false&marine=false) exposure view, where Power/Transmission/Poles are being displayed in the map, but are flagged as not displayed by the grey eye with a line through it. 

![not_hidden_jsrat](https://github.com/user-attachments/assets/d0de534b-da2a-4ed9-b591-1ea47303f591)

**Comment by eatyourgreens** [comment]
Seems to have been a bug for a while. I went back as far as version 0.4.8 and could still reproduce this bug.
